version: '3.9'
services:

  mongo:
    build: .
    image: mongocustom:1
    container_name: mongodb
    hostname: mongodb
    networks:
      - mongonet
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nbd
      - MONGO_INITDB_ROOT_PASSWORD=nbdpassword
    command: --config /etc/mongod.conf
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 2s
      retries: 5

  mongoinit:
      build: .
      image: mongocustom:1
      hostname: mongodbinit
      container_name: mongodbinit
      networks:
        - mongonet
      depends_on:
        mongo:
          condition: service_healthy
      command: >
        mongosh --host mongodb:27017 --username nbd --password nbdpassword --authenticationDatabase admin --eval
        '
        rs.initiate();
        '

  redis-stack:
    image: redis/redis-stack:latest
    volumes:
      - redis-stack-data:/bitnami/redis/data
    ports:
      - "8001:8001"
      - "6379:6379"
    networks:
      - redisnet

volumes:
  redis-stack-data:
    driver: local

networks:
  mongonet: {}
  redisnet: {}